/* One-shot generator: reads Maa Sheetla `components/india-geometry.ts`
   (INDIA_STATES, 35 polygons, ~244 KB) and writes a simplified state layer to
   src/components/map/india-states.ts. Same 760x860 Mercator viewBox, so the
   output sits exactly under the verbatim NATION_PATH in india-outline.ts.

   Run: `npm run generate:states -- <path-to-india-geometry.ts>`
   (default `../maa-sheetla/components/india-geometry.ts`; the file can also be
   fetched with `gh api -H "Accept: application/vnd.github.raw"
   repos/princepatel04477-web/maa_sheetla/contents/components/india-geometry.ts`).

   Simplification: Douglas–Peucker per ring at TOLERANCE viewBox units, rings
   whose bounding box is smaller than MIN_RING_EXTENT dropped (the nation
   outline and ISLET_MARKERS already carry the islands), one decimal place.
   Neighbouring borders are simplified independently; at this tolerance the
   seams stay well under a screen pixel at every size the map renders. */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const TOLERANCE = 0.7;
const MIN_RING_EXTENT = 3;

interface SourceState {
  id: string;
  name: string;
  d: string;
}

type Point = readonly [number, number];

function parseRings(d: string): Point[][] {
  const rings: Point[][] = [];
  for (const chunk of d.split(/Z/i)) {
    const nums = chunk.match(/-?\d+(?:\.\d+)?/g);
    if (nums === null || nums.length < 6) continue;
    const ring: Point[] = [];
    for (let i = 0; i + 1 < nums.length; i += 2) {
      ring.push([Number(nums[i]), Number(nums[i + 1])]);
    }
    rings.push(ring);
  }
  return rings;
}

function perpendicularDistance(p: Point, a: Point, b: Point): number {
  const dx = b[0] - a[0];
  const dy = b[1] - a[1];
  const len = Math.hypot(dx, dy);
  if (len === 0) return Math.hypot(p[0] - a[0], p[1] - a[1]);
  return Math.abs(dy * p[0] - dx * p[1] + b[0] * a[1] - b[1] * a[0]) / len;
}

function douglasPeucker(points: readonly Point[], tolerance: number): Point[] {
  if (points.length <= 2) return [...points];
  const keep = new Uint8Array(points.length);
  keep[0] = 1;
  keep[points.length - 1] = 1;
  const stack: [number, number][] = [[0, points.length - 1]];
  while (stack.length > 0) {
    const range = stack.pop();
    if (range === undefined) break;
    const [start, end] = range;
    let maxDist = 0;
    let index = -1;
    const a = points[start];
    const b = points[end];
    if (a === undefined || b === undefined) continue;
    for (let i = start + 1; i < end; i += 1) {
      const p = points[i];
      if (p === undefined) continue;
      const dist = perpendicularDistance(p, a, b);
      if (dist > maxDist) {
        maxDist = dist;
        index = i;
      }
    }
    if (index !== -1 && maxDist > tolerance) {
      keep[index] = 1;
      stack.push([start, index], [index, end]);
    }
  }
  return points.filter((_, i) => keep[i] === 1);
}

function ringExtent(ring: readonly Point[]): number {
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  for (const [x, y] of ring) {
    minX = Math.min(minX, x);
    minY = Math.min(minY, y);
    maxX = Math.max(maxX, x);
    maxY = Math.max(maxY, y);
  }
  return Math.max(maxX - minX, maxY - minY);
}

function ringToPath(ring: readonly Point[]): string {
  return `M${ring.map(([x, y]) => `${x.toFixed(1)},${y.toFixed(1)}`).join("L")}Z`;
}

function readSource(path: string): SourceState[] {
  const text = readFileSync(path, "utf8");
  const start = text.indexOf("export const INDIA_STATES");
  const assign = text.indexOf("= [", start);
  const open = assign + 2;
  const close = text.indexOf("\n];", open);
  if (start === -1 || assign === -1 || close === -1) {
    throw new Error(`INDIA_STATES array not found in ${path}`);
  }
  const parsed: unknown = JSON.parse(text.slice(open, close + 2));
  if (!Array.isArray(parsed)) throw new Error("INDIA_STATES is not an array");
  return parsed.map((entry: unknown): SourceState => {
    if (typeof entry !== "object" || entry === null) throw new Error("bad state entry");
    const { id, name, d } = entry as Record<string, unknown>;
    if (typeof id !== "string" || typeof name !== "string" || typeof d !== "string") {
      throw new Error("state entry missing id/name/d");
    }
    return { id, name, d };
  });
}

function main(): void {
  const root = join(dirname(fileURLToPath(import.meta.url)), "..");
  const sourcePath = process.argv[2] ?? join(root, "../maa-sheetla/components/india-geometry.ts");
  const states = readSource(sourcePath);

  let before = 0;
  let after = 0;
  const lines: string[] = [];
  lines.push("/* GENERATED by scripts/generate-states.mts — do not edit by hand.");
  lines.push("   Simplified from Maa Sheetla `components/india-geometry.ts` INDIA_STATES");
  lines.push(`   (Douglas–Peucker ${String(TOLERANCE)} units, same 760x860 viewBox). */`);
  lines.push("");
  lines.push("export interface StateShape {");
  lines.push("  id: string;");
  lines.push("  name: string;");
  lines.push("  d: string;");
  lines.push("}");
  lines.push("");
  lines.push("export const INDIA_STATES: readonly StateShape[] = [");
  for (const state of states) {
    before += state.d.length;
    const rings = parseRings(state.d);
    const largest = Math.max(...rings.map(ringExtent));
    const kept = rings
      .filter((ring) => {
        const extent = ringExtent(ring);
        return extent >= MIN_RING_EXTENT || extent === largest;
      })
      .map((ring) => douglasPeucker(ring, TOLERANCE))
      .filter((ring) => ring.length >= 3);
    const d = kept.map(ringToPath).join("");
    after += d.length;
    lines.push(
      `  { id: ${JSON.stringify(state.id)}, name: ${JSON.stringify(state.name)}, d: ${JSON.stringify(d)} },`,
    );
  }
  lines.push("];");
  lines.push("");

  writeFileSync(join(root, "src/components/map/india-states.ts"), `${lines.join("\n")}\n`);
  console.log(
    `wrote src/components/map/india-states.ts — ${String(states.length)} states, ${String(Math.round(before / 1024))} KB → ${String(Math.round(after / 1024))} KB of path data`,
  );
}

main();
